---
- name: set config and keys paths
  set_fact:
    ceph_config_key: /etc/ceph/{{ cluster }}.mgr.{{ ansible_hostname }}.keyring

- name: stat for ceph config and keys
  local_action: stat path={{ fetch_directory }}/docker_mon_files/{{ ceph_config_key }}
  changed_when: false
  become: false
  failed_when: false
  always_run: true
  register: statconfig

- name: try to fetch ceph config and keys
  copy:
    src: "{{ fetch_directory }}/docker_mon_files/{{ item.0 }}"
    dest: "{{ item.0 }}"
    owner: root
    group: root
    mode: 0644
  changed_when: false
  with_together:
    - "{{ ceph_config_key }}"
    - "{{ statconfig.results }}"
  when: item.1.stat.exists == true
