---
##########
# DOCKER #
##########

mgr_containerized_deployment: false
mgr_containerized_deployment_with_kv: false
kv_type: etcd
kv_endpoint: 127.0.0.1
ceph_docker_image: "ceph/daemon"
ceph_docker_image_tag: latest
ceph_docker_on_openstack: false
ceph_config_keys: [] # DON'T TOUCH ME
